spring:
  application:
    name: dragon_ball
  datasource:
    url: jdbc:mysql://localhost:3306/dragon_ball?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

security:
  jwt:
    secret-key: 586B633A8F3D2E7A1B4C9F0E5D8A2B7C4E6F1A3D9B8C2E5F7A0D3B6C9E2F4A1
    token-expiration: 600000